server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

spring:
  datasource:
    name: dylan
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: auth-moudle

zipkin:
  base-url: http://localhost:9411/
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0



