server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 0000
  routes:
    auth-route:
      path: /auth/**
      service-id: auth-moudle

    user-route:
      path: /user/**
      service-id: user-moudle
  ratelimit:
    key-prefix: dylan-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      server-auth:
        limit: 10
        quota: 100
        refresh-interval: 60

spring:
  application:
    name: gate-server

  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    web:
      client:
        enabled: true

    sampler:
      probability: 1.0







