server:
  port: 9012

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/


#register to zipkin for check error log
zipkin:
  base-url: http://localhost:9411/
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

spring:
  application:
    name: email-moudle

#value of rest password url
dylan:
  auth:
    rest-pwd-url: http://localhost/resetPwd?resetPwdKey=

